const { chromium } = require('@playwright/test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const base = process.env.NRTH_TEST_URL || 'http://127.0.0.1:4173';
const output = path.join(__dirname, 'artifacts/verified');
const checks = [];
function check(condition, label) { assert.ok(condition, label); checks.push(label); }
(async () => {
  fs.mkdirSync(output, { recursive: true });
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || '/usr/bin/chromium', args: ['--no-sandbox', '--disable-dev-shm-usage'] });
  try {
    const context = await browser.newContext({ viewport: { width: 1505, height: 1045 }, deviceScaleFactor: 1 });
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
    const capture = name => page.screenshot({ path: path.join(output, name + '.png') });
    await page.goto(base, { waitUntil: 'networkidle' });
    await page.waitForFunction(() => document.querySelector('[data-hero-scene]').dataset.sceneState === 'ready');
    check((await page.locator('h1').innerText()).includes('Ideas take shape.'), 'Home headline renders');
    check(await page.locator('.brand img').first().evaluate(img => img.complete && img.naturalWidth > 0), 'NRTH logo loads');
    check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Desktop has no horizontal overflow');
    const before = await capture('home-desktop');
    await page.locator('[data-hero-scene]').hover({ position: { x: 100, y: 100 } });
    await page.waitForTimeout(450);
    const after = await capture('home-pointer');
    check(!before.equals(after), 'Live scene changes with time and pointer interaction');
    await page.getByRole('button', { name: 'Pause motion', exact: true }).first().click();
    await page.waitForTimeout(1100);
    check(await page.evaluate(() => document.documentElement.classList.contains('motion-paused')), 'Motion pause works');
    await capture('home-paused');
    await page.locator('#ecosystem').scrollIntoViewIfNeeded();
    await page.waitForTimeout(300);
    check(await page.locator('#ecosystem').isVisible(), 'Scrolling reaches the venture ecosystem');
    await page.getByRole('tab', { name: /TMS/ }).click();
    check(await page.locator('#panel-nrth-tms').isVisible(), 'Project explorer switches to TMS');
    await page.keyboard.press('ArrowRight');
    check(await page.getByRole('tab', { name: /Telematics/ }).getAttribute('aria-selected') === 'true', 'Explorer keyboard navigation selects Telematics');
    await page.getByRole('button', { name: 'Next project', exact: true }).click();
    check(await page.locator('#panel-nrth-logistics').isVisible(), 'Explorer next control selects Logistics');
    await page.getByRole('button', { name: 'Previous project', exact: true }).click();
    check((await page.locator('[data-explorer-count]').innerText()).includes('03 / 09'), 'Explorer previous control updates its count');
    await page.getByRole('tab', { name: /Health/ }).click();
    await capture('home-ecosystem');
    await page.goto(base + '/projects', { waitUntil: 'networkidle' });
    check(await page.locator('.project-row:visible').count() === 9, 'All nine projects listed');
    await page.getByRole('button', { name: 'List', exact: true }).click();
    check(await page.locator('[data-project-directory]').getAttribute('data-directory-view') === 'list', 'Directory switches to list view');
    await page.getByRole('button', { name: 'Grid', exact: true }).click();
    await page.getByRole('button', { name: 'Mobility', exact: true }).click();
    check(await page.locator('.project-row:visible').count() === 4, 'Mobility filter returns four projects');
    await page.locator('[data-project-search]').fill('fleet');
    check(await page.locator('.project-row:visible').count() === 1, 'Search finds Fleet');
    await page.locator('[data-project-search]').fill('not-a-project');
    check(await page.locator('[data-project-empty]').isVisible(), 'Empty search state works');
    await page.getByRole('button', { name: 'All', exact: true }).click();
    await page.locator('[data-project-search]').fill('');
    await page.getByRole('link', { name: /NRTH Health/ }).first().click();
    check(page.url().endsWith('/projects/nrth-health'), 'Project navigation works');
    await capture('project-desktop');
    await page.locator('summary').filter({ hasText: 'What is available today?' }).click();
    check(await page.getByRole('link', { name: 'Contact NRTH', exact: true }).isVisible(), 'Project availability FAQ reveals its contact path');
    await page.getByRole('link', { name: 'Discuss NRTH Health' }).click();
    check(await page.locator('#project').inputValue() === 'nrth-health', 'Project inquiry is preselected');
    await page.locator('#name').fill('Website reviewer');
    await page.locator('#email').fill('reviewer@example.com');
    const message = 'I would like to discuss the current scope of NRTH Health.';
    await page.locator('#message').fill(message);
    await page.getByRole('button', { name: 'Prepare inquiry' }).click();
    check((await page.locator('[data-inquiry-preview]').innerText()).includes(message), 'Inquiry review includes the message');
    check((await page.locator('[data-inquiry-email]').getAttribute('href')).startsWith('mailto:hello@nrth.group?'), 'General inquiry uses hello inbox');
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('link', { name: 'Save a copy' }).click();
    const download = await downloadPromise;
    await download.saveAs(path.join(output, 'nrth-inquiry.txt'));
    check(fs.readFileSync(path.join(output, 'nrth-inquiry.txt'), 'utf8').includes(message), 'Inquiry download preserves message');
    await page.getByRole('button', { name: 'Edit message' }).click();
    check(!(await page.locator('[data-inquiry-result]').isVisible()), 'Edit closes inquiry review');
    await page.locator('#project').selectOption('partnership');
    await page.getByRole('button', { name: 'Prepare inquiry' }).click();
    check((await page.locator('[data-inquiry-email]').getAttribute('href')).startsWith('mailto:partnerships@nrth.group?'), 'Partnership routes to partnerships inbox');
    await capture('contact-ready');
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto(base, { waitUntil: 'networkidle' });
    await capture('home-mobile');
    check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile home has no horizontal overflow');
    await page.getByRole('button', { name: 'Menu', exact: true }).click();
    check(await page.locator('#mobile-navigation').isVisible(), 'Mobile navigation opens');
    await capture('menu-mobile');
    await page.keyboard.press('Escape');
    check(!(await page.locator('#mobile-navigation').isVisible()), 'Escape closes mobile navigation');
    check(await page.getByRole('button', { name: 'Menu', exact: true }).evaluate(el => el === document.activeElement), 'Menu returns keyboard focus');
    await page.goto(base + '/projects', { waitUntil: 'networkidle' });
    check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile projects have no horizontal overflow');
    await capture('projects-mobile');
    const reduced = await browser.newContext({ viewport: { width: 1505, height: 1045 }, reducedMotion: 'reduce' });
    const rp = await reduced.newPage();
    await rp.goto(base, { waitUntil: 'networkidle' });
    check(await rp.locator('canvas').count() === 0, 'Reduced motion avoids animated canvas');
    await rp.screenshot({ path: path.join(output, 'home-reduced.png') });
    const mobile = await browser.newContext({ viewport: { width: 390, height: 844 } });
    const mp = await mobile.newPage();
    const mobileRequests = [];
    mp.on('request', request => mobileRequests.push(request.url()));
    await mp.goto(base, { waitUntil: 'networkidle' });
    check(await mp.locator('canvas').count() === 1 && !mobileRequests.some(url => url.includes('three.module')), 'Mobile uses lightweight continuous geometry without Three.js');
    const motionBefore = await mp.locator('[data-hero-scene]').screenshot();
    await mp.evaluate(() => scrollTo({ top: (document.querySelector('[data-story]').offsetHeight-innerHeight)*.14, behavior: 'instant' }));
    await mp.waitForFunction(() => Number(document.querySelector('[data-story]').dataset.motionProgress) > .137);
    check(!motionBefore.equals(await mp.locator('[data-hero-scene]').screenshot()), 'Mobile geometry visibly transforms with scroll');
    await mp.screenshot({ path: path.join(output, 'home-mobile-motion.png') });
    check(await mp.getByRole('tablist').getAttribute('aria-orientation') === 'horizontal', 'Mobile explorer has horizontal keyboard orientation');
    await mp.getByRole('tab', { name: /Events/ }).click();
    check(await mp.locator('#panel-nrth-events').isVisible(), 'Mobile explorer can reach the ninth project');
    await mp.locator('#panel-nrth-events').scrollIntoViewIfNeeded();
    await mp.screenshot({ path: path.join(output, 'explorer-mobile.png') });
    const noJS = await browser.newContext({ javaScriptEnabled: false });
    const np = await noJS.newPage();
    await np.goto(base + '/projects');
    check(await np.locator('.project-row:visible').count() === 9, 'Project content remains readable without JavaScript');
    for (const name of ['Health', 'TMS', 'Telematics', 'Logistics', 'Systems', 'Labs', 'Chemicals', 'Fleet', 'Events']) {
      const slug = 'nrth-' + name.toLowerCase();
      const response = await context.request.get(base + '/projects/' + slug);
      const html = await response.text();
      check(response.ok() && html.includes('NRTH ' + name) && html.includes('https://nrth.group/projects/' + slug), name + ' page and canonical URL available');
    }
    await page.goto(base + '/projects?field=Mobility', { waitUntil: 'networkidle' });
    check(await page.locator('.project-row:visible').count() === 4, 'Field links prefilter the project directory');
    check(errors.length === 0, 'No browser runtime or console errors');
    fs.writeFileSync(path.join(output, 'results.json'), JSON.stringify({ result: 'passed', checks, errors }, null, 2));
    console.log(`${checks.length} browser checks passed.`);
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
