const {chromium}=require('@playwright/test');const assert=require('node:assert/strict');const fs=require('node:fs');
const base=process.env.NRTH_TEST_URL||'http://127.0.0.1:4173';const out='artifacts/brand-story';const checks=[];function check(value,label){assert.ok(value,label);checks.push(label);}
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});try{
 const context=await browser.newContext({viewport:{width:1505,height:1045}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.goto(base,{waitUntil:'networkidle'});await page.waitForFunction(()=>document.querySelector('[data-hero-scene]').dataset.sceneState==='ready');
 async function scrub(p,name){const y=await page.locator('[data-story]').evaluate((el,p)=>el.offsetTop+(el.offsetHeight-innerHeight)*p,p);await page.evaluate(y=>scrollTo({top:y,behavior:'instant'}),y);await page.waitForFunction(p=>Math.abs(Number(document.querySelector('[data-story]').dataset.motionProgress)-p)<.003,p,{timeout:15000});await page.waitForTimeout(150);if(name)await page.screenshot({path:`${out}/${name}.png`});}
 const canvas=page.locator('canvas');const canvasElement=await canvas.elementHandle();
 await scrub(0,'final-initial');check(await page.locator('.brand-static path').count()===4,'The opening and accessible fallback include all four NRTH letters');check(await page.locator('.brand img').first().isVisible(),'NRTH identity remains in the opening');check(await page.locator('.brand-static').evaluate(el=>getComputedStyle(el).visibility)==='hidden','Live N–R–T–H is present from the opening, without a poster takeover');
 const poses=[];
 for(let i=0;i<10;i++){await scrub(i/9,`pose-${i}`);check(await page.locator('[data-story]').getAttribute('data-chapter')===String(i),`Chapter ${i} matches its geometry`);check(await page.locator('canvas').evaluate((el,original)=>el===original,canvasElement),'The same canvas persists through the transformation');poses.push(await page.locator('[data-hero-scene]').screenshot());}
 check(poses.slice(1).every((image,i)=>!image.equals(poses[i])),'All consecutive keyframes have visibly different geometry');
 await scrub(.055,'half-morph');check(Number(await page.locator('[data-hero-scene]').getAttribute('data-blend'))>.4&&Number(await page.locator('[data-hero-scene]').getAttribute('data-blend'))<.6,'The letters have genuine intermediate geometry before becoming rings');const between=await page.locator('[data-hero-scene]').screenshot();check(!between.equals(poses[0])&&!between.equals(poses[1]),'The intermediate pose differs from both letter and ring endpoints');
 await scrub(4/9,'reverse-mobility');check(await page.locator('[data-hero-scene]').getAttribute('data-pose')==='4','Reverse scroll restores the mobility pose');
 for(let i=0;i<6;i++){await page.locator(`[data-industry="${i}"]`).click();await page.waitForFunction(i=>Math.abs(Number(document.querySelector('[data-story]').dataset.motionProgress)-(i+3)/9)<.003,i);check(await page.locator(`[data-industry="${i}"]`).getAttribute('aria-current')==='true',`Industry ${i} navigates the continuous story`);}
 await scrub(3/9);const ring=page.locator('[data-industry="1"] .nav-ring');const width=await ring.evaluate(el=>el.getBoundingClientRect().width);await page.locator('[data-industry="1"]').hover();await page.waitForTimeout(650);check(await ring.evaluate(el=>el.getBoundingClientRect().width)>width+10,'Hover turns a ring into an underline');
 const beforePointer=await page.locator('[data-hero-scene]').screenshot();await page.locator('[data-hero-scene]').hover({position:{x:1300,y:600}});await page.waitForTimeout(400);check(!beforePointer.equals(await page.locator('[data-hero-scene]').screenshot()),'The persistent strands respond to pointer perspective');
 await page.locator('[data-industry="2"]').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('[data-story]').dataset.chapter==='5');check(await page.locator('[data-industry="2"]').evaluate(el=>el===document.activeElement),'Keyboard selection retains focus on its industry control');
 await page.locator('[data-explorer]').scrollIntoViewIfNeeded();
 await page.locator('.explorer-stage').scrollIntoViewIfNeeded();await page.waitForTimeout(250);await page.getByRole('tab',{name:/TMS/}).click();check(await page.locator('[data-explorer]').getAttribute('data-transition')==='running','Gallery selection starts a coordinated transition');check(await page.locator('.explorer-selection').evaluate(el=>parseFloat(el.style.translate.split(' ')[1])>40),'The explorer selection marker moves to the chosen venture');await page.waitForTimeout(280);await page.screenshot({path:`${out}/gallery-transition.png`});await page.getByRole('tab',{name:/Fleet/}).click();await page.getByRole('tab',{name:/Health/}).click();await page.waitForTimeout(1000);check(await page.locator('.explorer-outgoing').count()===0,'Rapid venture switches leave no stale outgoing panels');check(await page.locator('[data-project-panel]:not([hidden])').count()===1,'Exactly one active project remains after rapid switching');
 await page.locator('.explorer-image:visible').hover({position:{x:100,y:100}});await page.waitForTimeout(300);check(await page.locator('.explorer-image:visible').evaluate(el=>Math.abs(Number(el.style.getPropertyValue('--pointer-x')))>.1),'The artwork responds to pointer position');await page.screenshot({path:`${out}/gallery-pointer.png`});
 const lab=page.locator('.lab-feature[data-scroll-feature]');await lab.scrollIntoViewIfNeeded();await page.waitForTimeout(300);const before=await lab.locator('.lab-visual>img').evaluate(el=>getComputedStyle(el).transform);await page.evaluate(()=>scrollBy({top:260,behavior:'instant'}));await page.waitForTimeout(300);const after=await lab.locator('.lab-visual>img').evaluate(el=>getComputedStyle(el).transform);check(before!==after,'Labs artwork transforms continuously with scroll');await page.screenshot({path:`${out}/labs-motion.png`});
 await scrub(8/9);await page.locator('.story-bottom [data-motion-toggle]').click();check(!await page.evaluate(()=>document.documentElement.classList.contains('motion-active')),'Pause removes the scroll choreography');check(await page.locator('[data-story]').evaluate(el=>el.offsetHeight<=innerHeight+5),'Pause replaces the pinned scene with a compact readable opening');check(await page.locator('.story-opening').isVisible(),'Opening copy stays readable after pause');check(await page.evaluate(()=>scrollY<5),'Pausing late in the story returns to the readable compact identity');await page.screenshot({path:`${out}/paused.png`});
 await page.locator('.story-bottom [data-motion-toggle]').click();await page.locator('[data-explorer]').scrollIntoViewIfNeeded();await page.getByRole('tab',{name:/TMS/}).click();await page.waitForTimeout(950);await page.evaluate(()=>addEventListener('pageswap',()=>sessionStorage.setItem('nrth-test-source-image',document.querySelector('[data-transition-source]')?.getAttribute('src')||''),{once:true}));await page.locator('#panel-nrth-tms .explorer-caption .text-link').click();await page.waitForURL('**/projects/nrth-tms');check(await page.evaluate(()=>sessionStorage.getItem('nrth-test-source-image')?.includes('mobility-art')),'The outgoing navigation snapshot uses TMS artwork, not an icon');check(await page.locator('.venture-art>img').evaluate(el=>getComputedStyle(el).viewTransitionName)==='nrth-artwork','The Discover text action shares the actual artwork rather than its arrow icon');check(await page.locator('html').getAttribute('data-shared-transition')==='running'||await page.locator('html').getAttribute('data-shared-transition')==='finished','The browser runs the actual shared-element page transition');await page.screenshot({path:`${out}/artwork-navigation.png`});await page.waitForTimeout(900);check(await page.locator('.venture-title h1').isVisible(),'The venture detail remains readable after the transition');await context.close();
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const mp=await mobile.newPage();const requests=[];mp.on('request',r=>requests.push(r.url()));mp.on('pageerror',e=>errors.push(e.message));await mp.goto(base,{waitUntil:'networkidle'});check(!requests.some(url=>url.includes('three.module')),'Touch uses the lightweight continuous renderer');await mp.evaluate(()=>scrollTo(0,(document.querySelector('[data-story]').offsetHeight-innerHeight)*4/9));await mp.waitForFunction(()=>document.querySelector('[data-story]').dataset.chapter==='4');await mp.waitForTimeout(300);check(await mp.locator('[data-hero-scene]').getAttribute('data-pose')==='4','Touch continuously reaches the mobility symbol');check(await mp.locator('.industry-nav').getAttribute('aria-hidden')==='false','The six industry controls become available on touch');await mp.screenshot({path:`${out}/final-mobile-mobility.png`});await mp.locator('[data-industry="3"]').tap();await mp.waitForFunction(()=>document.querySelector('[data-story]').dataset.chapter==='6');check(await mp.locator('[data-industry="3"]').getAttribute('aria-current')==='true','Touch selection navigates to Materials');await mobile.close();
 const reduced=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});const rp=await reduced.newPage();await rp.goto(base,{waitUntil:'networkidle'});check(await rp.locator('canvas').count()===0,'Reduced motion loads no animated canvas');check(await rp.locator('[data-story]').evaluate(el=>el.offsetHeight<=innerHeight+5),'Reduced motion omits the pinned scroll track');await rp.screenshot({path:`${out}/reduced-mobile.png`});await reduced.close();
 const nojs=await browser.newContext({viewport:{width:1505,height:1045},javaScriptEnabled:false});const np=await nojs.newPage();await np.goto(base);check(await np.locator('.story-bottom a[href="/projects"]').isVisible(),'The venture action works without JavaScript');check(await np.locator('.footer-projects a').count()===9,'All nine venture links remain available without JavaScript');await nojs.close();
 const responsive=await browser.newContext({reducedMotion:'reduce'});const bp=await responsive.newPage();for(const width of [390,768,1024,1505]){await bp.setViewportSize({width,height:844});await bp.goto(base);check(await bp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`No horizontal overflow at ${width}px`);}await responsive.close();
 const editorial=await browser.newContext({viewport:{width:1505,height:1045}});const ep=await editorial.newPage();ep.on('pageerror',e=>errors.push(e.message));
 for(const [route,label] of [['/approach','Approach'],['/insights/clarity-is-a-design-decision','Article']]){await ep.goto(base+route,{waitUntil:'networkidle'});const heading=ep.locator('.editorial-heading h2').first();await heading.scrollIntoViewIfNeeded();check(await heading.locator('.motion-line>span').evaluateAll(elements=>elements.every(el=>Number(getComputedStyle(el).opacity)>.95)),`${label} titles remain visible with motion enabled`);await ep.screenshot({path:`${out}/${label.toLowerCase()}-motion.png`});}await editorial.close();
 check(errors.length===0,'No browser runtime or console errors in the motion journey');fs.writeFileSync(`${out}/results.json`,JSON.stringify({checks,errors},null,2));console.log(checks.length+' motion checks passed');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
